import { GoogleGenAI } from "@google/genai";
import { AI_SETTINGS } from '../constants/note';
import { parseBase64Image, createBase64Url } from '../utils/noteHelpers';

class GeminiError extends Error {
  constructor(message: string, public readonly cause?: unknown) {
    super(message);
    this.name = 'GeminiError';
  }
}

export class GeminiService {
  private ai: GoogleGenAI | null = null;
  private apiKey: string | null = null;

  private init() {
    if (this.ai) return;

    if (!this.apiKey) {
      this.apiKey = this.loadApiKey();
    }

    if (!this.apiKey) {
      throw new GeminiError('API key not found. Please set GEMINI_API_KEY in your .env file');
    }

    this.ai = new GoogleGenAI({ apiKey: this.apiKey });
  }

  private loadApiKey(): string | null {
    // Try to get from import.meta.env (Vite)
    if (import.meta.env?.VITE_GEMINI_API_KEY) {
      return import.meta.env.VITE_GEMINI_API_KEY;
    }

    // Try to get from window.env (if configured)
    if (typeof window !== 'undefined' && (window as any).env?.GEMINI_API_KEY) {
      return (window as any).env.GEMINI_API_KEY;
    }

    return null;
  }

  async editImage(base64Image: string, prompt: string): Promise<string> {
    try {
      this.init();

      if (!this.ai) {
        throw new GeminiError('Failed to initialize Gemini service');
      }

      const { data: imageData, mimeType } = parseBase64Image(base64Image);

      const response = await this.ai.models.generateContent({
        model: AI_SETTINGS.MODEL,
        contents: {
          parts: [
            {
              inlineData: {
                data: imageData,
                mimeType: mimeType,
              },
            },
            {
              text: prompt,
            },
          ],
        },
      });

      // Extract image from response
      const candidate = response.candidates?.[0];
      if (!candidate?.content?.parts) {
        throw new GeminiError('No content in AI response');
      }

      for (const part of candidate.content.parts) {
        if (part.inlineData?.data) {
          return createBase64Url(part.inlineData.data, part.inlineData.mimeType || 'image/png');
        }
      }

      throw new GeminiError('No image was generated by the AI');
    } catch (error) {
      if (error instanceof GeminiError) {
        throw error;
      }
      throw new GeminiError(
        'Failed to edit image with AI',
        error
      );
    }
  }
}

export const geminiService = new GeminiService();
